baseURL = "https://naif.soy"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Naif Alzahri"
theme = "hermit"
enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
publishDir = "docs"
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/


[author]
  name = "Naif"

[blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true
  nofollowLinks = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#494f5c"

  homeSubtitle = "Aspiring Web Developer/Data Scientist"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

# look here github.com/Track3/hermit#social-icons

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/nayif/"

  [[params.social]]
    name = "github"
    url = "https://github.com/Nayifff"

  [[params.social]]
    name = "email"
    url = "naif.a@columbia.edu"
    
[menu]

  [[menu.main]]
    identifier = "about"
    name = "about me"
    pre = "<i class='fa fa-heart'>I've graduated as a Mechanical Engineer. My learning curve and area of expertise didn't end there. Though I love everything related to physics and mechanical systems, my current passion lies in building software. I am interested in web development, data-analytics, and machine learning. I am committed to continuous learning and always try to do things that matter. 

I really enjoy exploring the outdoors, biking and snowboarding. I bike around New York City. Whenever I am indoors, I like to spend my time reading. I mostly read about history, cultures, and religions. I am fascinated by how cultures were developed and why the world is as we see it today. </i>"
    url = "/about/"
    weight = -110